export * from './ColorModelsPage/ColorModelsPage';
export * from './ColorPracticePage/ColorPracticePage';
export * from './FigureMovementPage/FigureMovementPage';
export * from './FirstPage/FirstPage';
export * from './FractalPage/FractalPage';
export * from './FractalPracticePage/FractalPracticePage';
export * from './FractalTestPage/FractalTestPage';
export * from './LastPage/LastPage';
export * from './MovePracticePage/MovePracticePage';